try
{
    // exception is thrown
}
catch(Exception ex)
{
    throw;
    throw ex;
}